import React, { useState, useContext, useEffect } from 'react';
import {
  View, Text, ScrollView, StyleSheet,
  TouchableOpacity, SafeAreaView, StatusBar, Alert,
} from 'react-native';
import { C } from '../constants/theme';
import { AppContext } from '../context/AppContext';
import { getAssessments, getPatients, deletePatient } from '../api';
import { ASSESSMENTS } from '../data/assessments';
import Avatar from '../components/Avatar';
import Card from '../components/Card';
import Badge from '../components/Badge';
import ProgressBar from '../components/ProgressBar';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import Btn from '../components/Btn';

export default function DoctorReviewScreen() {
  const { user, logout } = useContext(AppContext);
  const [tab, setTab] = useState('dashboard');
  const [assessments, setAssessments] = useState([]);
  const [patients, setPatients] = useState([]);
  const [selectedPatientID, setSelectedPatientID] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const [aData, pData] = await Promise.all([getAssessments(), getPatients()]);
        setAssessments(aData || []);
        setPatients(pData ? pData.filter(u => u.role === 'patient') : []);
      } catch (err) {
        console.error("Error fetching doctor data:", err);
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, []);

  const handleExportReport = async () => {
    if (!selectedPatient) return;
    try {
      const p = selectedPatient;
      const asses = assessments.filter(a => a.user?._id === p._id);
      
      const assesRows = asses.map(a => `
        <div style="border: 1px solid #eee; padding: 15px; border-radius: 10px; margin-bottom: 15px;">
          <div style="font-weight: bold; color: #444;">${a.assessmentType.toUpperCase()}</div>
          <div style="font-size: 24px; color: #2D5A27; margin: 5px 0;">Score: ${a.totalScore}</div>
          <div style="font-size: 14px; color: #666;">Severity: ${a.severity?.label || 'N/A'}</div>
          <div style="font-size: 12px; color: #999; margin-top: 5px;">Date: ${new Date(a.createdAt).toLocaleDateString()}</div>
        </div>
      `).join('');

      const html = `
        <html>
          <body style="font-family: sans-serif; padding: 40px; color: #333;">
            <h1 style="color: #2D5A27; border-bottom: 2px solid #2D5A27; padding-bottom: 10px;">Clinical Patient Report</h1>
            <div style="margin: 20px 0;">
              <p><strong>Patient Name:</strong> ${p.name}</p>
              <p><strong>Email:</strong> ${p.email}</p>
              <p><strong>Account Status:</strong> Active</p>
            </div>
            <h2 style="color: #444; margin-top: 30px;">Assessment History</h2>
            ${assesRows || '<p>No assessments completed yet.</p>'}
            <div style="margin-top: 50px; padding-top: 20px; border-top: 1px solid #eee; font-size: 11px; color: #999;">
              <p>Generated by MindBridge Provider Portal</p>
              <p>Confidential Medical Information - Restricted Access</p>
            </div>
          </body>
        </html>
      `;
      
      const { uri } = await Print.printToFileAsync({ html });
      await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
    } catch (err) {
      alert("Export failed");
    }
  };

  const handleDeletePatient = async () => {
    const confirmDelete = async () => {
      try {
        await deletePatient(selectedPatientID);
        setPatients(prev => prev.filter(p => p._id !== selectedPatientID));
        setSelectedPatientID(null);
      } catch (err) {
        if (Platform.OS === 'web') alert("Failed to delete patient");
        else Alert.alert("Error", "Failed to delete patient.");
      }
    };

    if (Platform.OS === 'web') {
      if (window.confirm("Are you sure you want to delete this patient and all their associated data? This action cannot be undone.")) {
        confirmDelete();
      }
    } else {
      Alert.alert(
        "Delete Patient",
        "Are you sure you want to delete this patient and all their associated data? This action cannot be undone.",
        [
          { text: "Cancel", style: "cancel" },
          { text: "Delete", style: "destructive", onPress: confirmDelete }
        ]
      );
    }
  };



  const selectedPatient = selectedPatientID ? patients.find(p => p._id === selectedPatientID) : null;
  const patientAssessments = assessments.filter(a => a.user?._id === selectedPatientID);
  const latestAssessment = patientAssessments[0]; 

  const mhScore = latestAssessment ? latestAssessment.totalScore : null;
  const mhBreakdown = latestAssessment ? latestAssessment.breakdown : {};
  const mhSev = latestAssessment ? latestAssessment.severity : null;

  const STATS = [
    { icon: '👥', label: 'Registered Patients', value: String(new Set(assessments.map(a => a.user?._id)).size), color: '#4F7FFF', bg: '#EEF2FF' },
    { icon: '✅', label: 'Completed',             value: String(assessments.length),          color: '#10B981', bg: '#D1FAE5' },
  ];

  const RECENT_ACTIVITY = assessments.slice(0, 5).map(a => ({
    time: new Date(a.createdAt).toLocaleDateString(),
    text: `${a.user?.name || 'A patient'} completed the ${ASSESSMENTS[a.assessmentType]?.name || a.assessmentType} assessment`,
    type: 'assessment',
  }));

  const tabs = [
    { key: 'dashboard', label: 'Dashboard', icon: '📊' },
    { key: 'patient', label: 'Patient Review', icon: '🩺' },
  ];

  return (
    <SafeAreaView style={styles.safe}>
      <StatusBar barStyle="light-content" backgroundColor="#1C3050" />

      {/* Header */}
      <View style={styles.header}>
        <View>
          <Text style={styles.headerLabel}>DOCTOR PORTAL</Text>
          <Text style={styles.headerName}>🩺 {user?.firstName} {user?.lastName}</Text>
        </View>
        <TouchableOpacity onPress={logout} style={styles.logoutBtn}>
          <Text style={styles.logoutText}>Logout</Text>
        </TouchableOpacity>
      </View>

      {/* Tab Bar */}
      <View style={styles.tabBar}>
        {tabs.map(t => (
          <TouchableOpacity
            key={t.key}
            onPress={() => setTab(t.key)}
            style={[styles.tab, tab === t.key && styles.tabActive]}
          >
            <Text style={styles.tabIcon}>{t.icon}</Text>
            <Text style={[styles.tabText, tab === t.key && styles.tabTextActive]}>{t.label}</Text>
          </TouchableOpacity>
        ))}
      </View>

      <ScrollView style={styles.scroll} showsVerticalScrollIndicator={false}>
        {tab === 'dashboard' && (
          <View>
            <Text style={styles.sectionLabel}>OVERVIEW</Text>
            <View style={styles.statsGrid}>
              {STATS.map((s, i) => (
                <View key={i} style={[styles.statCard, { backgroundColor: s.bg }]}>
                  <Text style={styles.statIcon}>{s.icon}</Text>
                  <Text style={[styles.statValue, { color: s.color }]}>{s.value}</Text>
                  <Text style={styles.statLabel}>{s.label}</Text>
                </View>
              ))}
            </View>
            <Text style={styles.sectionLabel}>RECENT ACTIVITY</Text>
            <View style={styles.activityCard}>
              {RECENT_ACTIVITY.map((item, i) => (
                <View key={i} style={[styles.activityRow, i < RECENT_ACTIVITY.length - 1 && styles.activityBorder]}>
                  <View style={[styles.activityDot, { backgroundColor: '#4F7FFF' }]} />
                  <View style={{ flex: 1 }}>
                    <Text style={styles.activityText}>{item.text}</Text>
                    <Text style={styles.activityTime}>{item.time}</Text>
                  </View>
                </View>
              ))}
            </View>
          </View>
        )}

        {tab === 'patient' && (
          <View>
            {!selectedPatient ? (
              <View style={{ paddingHorizontal: 20 }}>
                <Text style={styles.sectionLabel}>ALL PATIENTS ({patients.length})</Text>
                {patients.map(p => (
                  <TouchableOpacity key={p._id} style={styles.patientRow} onPress={() => setSelectedPatientID(p._id)}>
                    <Avatar name={p.name} size={40} fs={14} />
                    <View style={{ flex: 1, marginLeft: 12 }}>
                      <Text style={styles.patientRowName}>{p.name}</Text>
                      <Text style={styles.patientRowEmail}>{p.email}</Text>
                    </View>
                    <Text style={styles.chevron}>›</Text>
                  </TouchableOpacity>
                ))}
              </View>
            ) : (
              <View>
                <TouchableOpacity onPress={() => setSelectedPatientID(null)} style={styles.backButton}>
                  <Text style={styles.backButtonText}>← Back to all patients</Text>
                </TouchableOpacity>

                <Text style={styles.sectionLabel}>PATIENT PROFILE</Text>
                <Card style={styles.patientCard}>
                  <View style={{ flexDirection: 'row', alignItems: 'center' }}>
                    <Avatar name={selectedPatient.name} size={52} fs={18} />
                    <View style={{ marginLeft: 14, flex: 1 }}>
                      <Text style={styles.patientName}>{selectedPatient.name}</Text>
                      <Text style={styles.patientEmail}>{selectedPatient.email}</Text>
                    </View>
                  </View>
                </Card>

                {!latestAssessment ? (
                  <View style={styles.noAssessmentContainer}>
                    <Text style={styles.noAssessmentText}>No assessments completed yet.</Text>
                  </View>
                ) : (
                  <View>
                    <Text style={styles.sectionLabel}>LATEST RESULTS</Text>
                    <View style={styles.scoreCard}>
                      <Text style={styles.scoreVal}>{mhScore}/{ASSESSMENTS.mentalHealth.maxScore}</Text>
                      <View style={[styles.scoreBadge, { backgroundColor: mhSev?.bg || '#eee' }]}>
                        <Text style={[styles.scoreBadgeText, { color: mhSev?.color || '#333' }]}>{mhSev?.label}</Text>
                      </View>
                    </View>
                    
                    <Text style={styles.sectionLabel}>BREAKDOWN</Text>
                    <Card style={{ paddingVertical: 10 }}>
                      {Object.entries(mhBreakdown).map(([cat, data]) => (
                        <View key={cat} style={styles.catRow}>
                          <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 }}>
                            <Text style={{ fontSize: 13, fontWeight: '700' }}>{cat}</Text>
                            <Text style={{ fontSize: 13 }}>{data.score}/{data.count * 3}</Text>
                          </View>
                          <ProgressBar val={data.score} max={data.count * 3} color={C.sage} h={6} />
                        </View>
                      ))}
                    </Card>
                  </View>
                )}

                <View style={{ paddingHorizontal: 20, marginTop: 24, paddingBottom: 20, gap: 10 }}>
                  <Btn onPress={handleExportReport} variant="secondary">📄 Export Clinical Report (PDF)</Btn>
                  <TouchableOpacity onPress={handleDeletePatient} style={styles.deleteBtn}>
                    <Text style={styles.deleteBtnText}>🗑 Delete Patient Profile</Text>
                  </TouchableOpacity>
                  <Btn onPress={() => setSelectedPatientID(null)} variant="ghost">← Return to Dashboard</Btn>
                </View>
              </View>
            )}
          </View>
        )}
        <View style={{ height: 40 }} />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#1C3050' },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingTop: 12, paddingBottom: 16 },
  headerLabel: { fontSize: 11, color: 'rgba(255,255,255,0.5)', fontWeight: '700', letterSpacing: 1, marginBottom: 4 },
  headerName: { fontSize: 20, fontWeight: '800', color: '#fff' },
  logoutBtn: { paddingHorizontal: 14, paddingVertical: 8, backgroundColor: 'rgba(255,255,255,0.1)', borderRadius: 10, borderWidth: 1, borderColor: 'rgba(255,255,255,0.15)' },
  logoutText: { color: '#fff', fontSize: 13, fontWeight: '700' },
  tabBar: { flexDirection: 'row', backgroundColor: '#fff', borderBottomWidth: 1, borderBottomColor: '#E2E8F0' },
  tab: { flex: 1, paddingVertical: 12, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 6, borderBottomWidth: 2, borderBottomColor: 'transparent' },
  tabActive: { borderBottomColor: '#3562A0' },
  tabIcon: { fontSize: 16 },
  tabText: { fontSize: 13, fontWeight: '600', color: '#94A3B8' },
  tabTextActive: { color: '#3562A0', fontWeight: '800' },
  scroll: { flex: 1, backgroundColor: '#F8FAFC' },
  sectionLabel: { fontSize: 11, fontWeight: '700', color: '#94A3B8', letterSpacing: 1, marginTop: 20, marginBottom: 10, paddingHorizontal: 20 },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', paddingHorizontal: 14, gap: 10 },
  statCard: { width: '47%', borderRadius: 16, padding: 18, alignItems: 'flex-start' },
  statIcon: { fontSize: 24, marginBottom: 10 },
  statValue: { fontSize: 28, fontWeight: '800', marginBottom: 2 },
  statLabel: { fontSize: 12, color: '#64748B', fontWeight: '500' },
  activityCard: { marginHorizontal: 20, backgroundColor: '#fff', borderRadius: 16, overflow: 'hidden', shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 8, elevation: 2, marginBottom: 10 },
  activityRow: { flexDirection: 'row', alignItems: 'flex-start', padding: 16, gap: 12 },
  activityBorder: { borderBottomWidth: 1, borderBottomColor: '#F1F5F9' },
  activityDot: { width: 8, height: 8, borderRadius: 4, marginTop: 5 },
  activityText: { fontSize: 13, color: '#334155', fontWeight: '500', lineHeight: 18 },
  activityTime: { fontSize: 11, color: '#94A3B8', marginTop: 2 },
  patientRow: { backgroundColor: '#fff', borderRadius: 16, padding: 14, flexDirection: 'row', alignItems: 'center', marginBottom: 10, shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 8, elevation: 2 },
  patientRowName: { fontSize: 15, fontWeight: '700', color: '#1E293B' },
  patientRowEmail: { fontSize: 11, color: '#64748B', marginTop: 2 },
  chevron: { fontSize: 20, color: '#CBD5E1' },
  backButton: { marginHorizontal: 20, marginTop: 10, paddingVertical: 8 },
  backButtonText: { color: '#3562A0', fontSize: 13, fontWeight: '700' },
  patientCard: { marginHorizontal: 20 },
  patientName: { fontSize: 18, fontWeight: '800', color: C.charcoal },
  patientEmail: { fontSize: 13, color: C.muted },
  noAssessmentContainer: { padding: 40, alignItems: 'center' },
  noAssessmentText: { color: C.muted, textAlign: 'center', fontSize: 14 },
  scoreCard: { marginHorizontal: 20, backgroundColor: '#1C3050', borderRadius: 16, padding: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  scoreVal: { fontSize: 32, fontWeight: '800', color: '#fff' },
  scoreBadge: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8 },
  scoreBadgeText: { fontSize: 13, fontWeight: '800' },
  catRow: { marginBottom: 14, paddingHorizontal: 10 },
  deleteBtn: { alignItems: 'center', paddingVertical: 15, backgroundColor: C.dangerLight, borderRadius: 12, borderWidth: 1, borderColor: C.danger + '22' },
  deleteBtnText: { color: C.danger, fontWeight: '700' },
});
